import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { IWeatherSuccessRes, getWeather } from '@/server/weather'
import { GetServerSideProps } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const getServerSideProps: GetServerSideProps<{ data: IWeatherSuccessRes | null }> = async (context) => {
  /*const w = await getWeather({
    lang: context.req.headers['accept-language'] || "en",
    city: "Zonguldak"
  })
*/
  return {
    props: {
      data: null
    },
  }
}

export default function Home(props: IWeatherSuccessRes | null) {
  console.log(props)
  return (
    <>
      <Head>
        <title>Hava Durumu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-[90vh] flex flex-col justify-center items-center">
        <img src='/location.svg' className="w-2/6 h-2/6 max-w-sm" />
        <a className='mt-10 text-center'>Tarayıcınızdan konum erişim izni vererek aktif konumunuzdaki hava durumunu görebilirsiniz.</a>
        <button className='bg-purple-500 hover:bg-purple-600 py-2 px-4 rounded-md text-white mt-4'>Konum izni ver</button>
      </div>
    </>
  )
}
